TEXTS = {
    "ru": {
        "choose_language": "🌍 Выберите язык / Choose language",
        "language_selected": "🇷🇺 Русский язык выбран. Добро пожаловать в Exhanger 💰",
        "exchange_intro": "💱 Выберите валюту, которую хотите отправить.",
        "choose_to": "💱 Теперь выберите валюту, которую хотите получить.",
        "enter_amount": "✍️ Введите сумму обмена числом.",
        "enter_receive": "🏦 Введите реквизиты для получения:\n\n• криптокошелек\n• номер карты\n• банковские реквизиты",
        "choose_payment": "💳 Выберите способ оплаты.",
        "choose_card_submethod": "💳 Выберите способ перевода:\n\n• Перевод по номеру карты\n• Перевод в Telegram Wallet",
        "support": "🛟 Если у вас есть вопросы по обмену, оплате или срокам перевода, напишите в поддержку:\n{support}\n\n💵 При переводе на рубли доступна доставка наличных в разные регионы России. Для уточнения деталей свяжитесь с поддержкой.",
        "blocked": "⛔ Ваш доступ к боту ограничен. Если вы считаете это ошибкой, свяжитесь с поддержкой.",
        "no_active_request": "⚠️ У вас нет активной заявки на оплату.",
        "paid_thanks": "✅ Спасибо за оплату!\n\nВаш платеж отправлен на проверку.\nОператор проверит перевод и выполнит обмен.\n\n⏳ Обычно это занимает от 10 минут до 1 часа.\n\nЕсли у вас возникнут вопросы или пожелания — обратитесь в поддержку:\n{support}",
        "wallet_operator_msg": "💬 Выбран перевод через Telegram Wallet.\n\nВ ближайшее время вам напишет оператор для перевода.\n\nПожалуйста, ожидайте сообщение в Telegram.\nЕсли возникнут вопросы — поддержка:\n{support}",
        "referral": "🎁 *Реферальная программа*\n\nПриглашайте друзей и получайте более выгодные условия обмена.\n\n🔑 *Ваш код:* `{code}`\n🔗 *Ваша ссылка:*\n{link}\n\n👥 *Приглашено пользователей:* {invited}\n✅ *Завершённых обменов по рефералам:* {completed}\n\n💰 *Базовая комиссия:* {base_fee:.2f}%\n🎉 *Ваша скидка на комиссию:* {discount:.2f}%\n🔥 *Текущая комиссия:* {current_fee:.2f}%\n\nЧем больше друзей вы приглашаете, тем ниже ваша комиссия. Это живая система скидок, которая делает каждый следующий обмен ещё выгоднее. 🚀",
        "rates_intro": "📊 Выберите валюту, в которой показать котировки.",
        "rates_fmt": "📊 *Актуальные курсы в {quote}*\n\n{body}\n\n💰 Базовая комиссия обменника: 0.95%, может снижаться за счёт реферальной программы.",
        "same_currency": "⚠️ Нельзя выбрать одинаковую валюту для отправки и получения.",
        "invalid_currency": "⚠️ Пожалуйста, выберите валюту кнопкой снизу.",
        "invalid_amount": "⚠️ Введите сумму числом, например: 1500 или 0.25",
        "summary": "📄 *Предварительный расчет*\n\n📤 Отдаёте: *{amount_from} {from_cur}*\n📥 Получаете: *{amount_to} {to_cur}*\n📈 Рыночный курс: *1 {from_cur} = {market_rate} {to_cur}*\n💰 Ваша текущая комиссия: *{fee:.2f}%*\n\nТеперь введите реквизиты для получения.",
        "request_created": "✅ *Заявка создана*\n\nНомер заявки: *#{request_id}*\nСпособ оплаты: *{payment_method}*\n\n⚠️ Важно: отправляйте *точную сумму до копейки*.\nЛюбое отклонение может привести к задержке обработки платежа.\n\n🔗 Ссылка для оплаты:\n{payment_url}\n\nПосле оплаты нажмите кнопку снизу.",
        "card_number_payment": "💳 *Перевод по номеру карты*\n\n⚠️ Важно: отправляйте *точную сумму до копейки*.\nЛюбое отклонение может привести к задержке обработки платежа.\n\nКарта для перевода:\n`{card_number}`\n*(рубли)*\n\nПосле оплаты нажмите кнопку снизу.",
        "admin_new_paid": "🔔 *Новая оплаченная заявка*\n\nЗаявка: *#{request_id}*\nПользователь: {user_display}\nID: `{user_id}`\nПрофиль: {profile_link}\n\nОбмен: *{from_cur} → {to_cur}*\nСумма: *{amount_from} {from_cur}*\nК получению: *{amount_to} {to_cur}*\n\nРеквизиты клиента:\n`{receive_details}`\n\nСпособ оплаты: *{payment_method}*",
        "admin_wallet_urgent": "🚨 *СРОЧНАЯ ЗАЯВКА WALLET*\n\nЗаявка: *#{request_id}*\nПользователь: {user_display}\nID: `{user_id}`\nПрофиль: {profile_link}\n\nОбмен: *{from_cur} → {to_cur}*\nСумма: *{amount_from} {from_cur}*\nК получению: *{amount_to} {to_cur}*\n\nРеквизиты клиента:\n`{receive_details}`\n\n⚠️ Клиент ждёт перевода через Telegram Wallet. Свяжитесь с ним как можно быстрее.",
        "requests_header": "📚 *Последние заявки*",
        "requests_empty": "Заявок пока нет.",
        "request_row": "# {id} | {user_display}\n{from_cur} → {to_cur}\n{amount_from} {from_cur} → {amount_to} {to_cur}\nСтатус: {status}\nОплата: {payment_method} / {payment_submethod}\n",
        "admin_blocked": "⛔ Пользователь заблокирован.",
        "admin_unblocked": "✅ Пользователь разблокирован.",
        "admin_done": "✅ Заявка отмечена как выполненная.",
    },
    "en": {
        "choose_language": "🌍 Choose language / Выберите язык",
        "language_selected": "🇬🇧 English selected. Welcome to Exhanger 💰",
        "exchange_intro": "💱 Choose the currency you want to send.",
        "choose_to": "💱 Now choose the currency you want to receive.",
        "enter_amount": "✍️ Enter the exchange amount as a number.",
        "enter_receive": "🏦 Enter your receiving details:\n\n• crypto wallet\n• card number\n• bank details",
        "choose_payment": "💳 Choose your payment method.",
        "choose_card_submethod": "💳 Choose transfer method:\n\n• Transfer by card number\n• Transfer to Telegram Wallet",
        "support": "🛟 If you have questions about exchange, payment or transfer time, contact support:\n{support}\n\n💵 For RUB payouts, cash delivery to different regions of Russia may be available. Contact support for details.",
        "blocked": "⛔ Your access to the bot is restricted. If you think this is a mistake, contact support.",
        "no_active_request": "⚠️ You do not have an active payment request.",
        "paid_thanks": "✅ Thank you for your payment!\n\nYour payment has been sent for verification.\nAn operator will check the transfer and complete the exchange.\n\n⏳ This usually takes 10 minutes to 1 hour.\n\nIf you have any questions or suggestions, contact support:\n{support}",
        "wallet_operator_msg": "💬 Telegram Wallet transfer selected.\n\nAn operator will contact you shortly to make the transfer.\n\nPlease wait for a message in Telegram.\nIf you have questions, contact support:\n{support}",
        "referral": "🎁 *Referral Program*\n\nInvite friends and unlock better exchange conditions.\n\n🔑 *Your code:* `{code}`\n🔗 *Your link:*\n{link}\n\n👥 *Invited users:* {invited}\n✅ *Completed referral exchanges:* {completed}\n\n💰 *Base fee:* {base_fee:.2f}%\n🎉 *Your fee discount:* {discount:.2f}%\n🔥 *Your current fee:* {current_fee:.2f}%\n\nThe more friends you invite, the lower your fee becomes. It is a live discount system that makes every next exchange more profitable. 🚀",
        "rates_intro": "📊 Choose the currency in which to show the rates.",
        "rates_fmt": "📊 *Live rates in {quote}*\n\n{body}\n\n💰 Base exchange fee: 0.95%, can be reduced through the referral program.",
        "same_currency": "⚠️ You cannot choose the same sending and receiving currency.",
        "invalid_currency": "⚠️ Please choose a currency using the buttons below.",
        "invalid_amount": "⚠️ Enter the amount as a number, for example: 1500 or 0.25",
        "summary": "📄 *Preliminary calculation*\n\n📤 You send: *{amount_from} {from_cur}*\n📥 You receive: *{amount_to} {to_cur}*\n📈 Market rate: *1 {from_cur} = {market_rate} {to_cur}*\n💰 Your current fee: *{fee:.2f}%*\n\nNow enter your receiving details.",
        "request_created": "✅ *Request created*\n\nRequest number: *#{request_id}*\nPayment method: *{payment_method}*\n\n⚠️ Important: send the *exact amount to the cent*.\nAny difference may delay payment processing.\n\n🔗 Payment link:\n{payment_url}\n\nAfter payment, press the button below.",
        "card_number_payment": "💳 *Transfer by card number*\n\n⚠️ Important: send the *exact amount to the cent*.\nAny difference may delay payment processing.\n\nCard for transfer:\n`{card_number}`\n*(RUB)*\n\nAfter payment, press the button below.",
        "admin_new_paid": "🔔 *New paid request*\n\nRequest: *#{request_id}*\nUser: {user_display}\nID: `{user_id}`\nProfile: {profile_link}\n\nExchange: *{from_cur} → {to_cur}*\nAmount: *{amount_from} {from_cur}*\nTo receive: *{amount_to} {to_cur}*\n\nClient details:\n`{receive_details}`\n\nPayment method: *{payment_method}*",
        "admin_wallet_urgent": "🚨 *URGENT WALLET REQUEST*\n\nRequest: *#{request_id}*\nUser: {user_display}\nID: `{user_id}`\nProfile: {profile_link}\n\nExchange: *{from_cur} → {to_cur}*\nAmount: *{amount_from} {from_cur}*\nTo receive: *{amount_to} {to_cur}*\n\nClient details:\n`{receive_details}`\n\n⚠️ The client is waiting for a Telegram Wallet transfer. Please contact them as soon as possible.",
        "requests_header": "📚 *Latest requests*",
        "requests_empty": "No requests yet.",
        "request_row": "# {id} | {user_display}\n{from_cur} → {to_cur}\n{amount_from} {from_cur} → {amount_to} {to_cur}\nStatus: {status}\nPayment: {payment_method} / {payment_submethod}\n",
        "admin_blocked": "⛔ User blocked.",
        "admin_unblocked": "✅ User unblocked.",
        "admin_done": "✅ Request marked as completed.",
    },
}
